### ISSUE TITLE
Error in "output,prediction=model_processing(img_pre,0.3,0.3,1)"

### ISSUE THREAD

**Issue by emamangiapia** [akshay-gupta123/Face-Mask-Detection#1]
Hi, when I run your code, I get this error: 
`output,prediction=model_processing(img_pre,0.3,0.3,1)`

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-a607639a0570> in <module>()
----> 1 output,prediction=model_processing(img_pre,0.3,0.3,1)

9 frames
<ipython-input-18-532dcba27e0f> in model_processing(img, confidence, iou, show_yolo_result)
      1 def model_processing(img,confidence,iou,show_yolo_result=0):
      2   torch_image = torch.from_numpy(np.ascontiguousarray(img.transpose(2, 0, 1))).to(device).unsqueeze(0)
----> 3   prediction = model(torch_image)
      4   output = non_max_suppression(prediction[0], conf_thres=confidence, iou_thres=iou)
      5   if show_yolo_result :

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.__class__():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/content/yolov5/models/common.py in forward(self, imgs, size, augment, profile)
    255         if isinstance(imgs, torch.Tensor):  # torch
    256             with amp.autocast(enabled=p.device.type != 'cpu'):
--> 257                 return self.model(imgs.to(p.device).type_as(p), augment, profile)  # inference
    258 
    259         # Pre-process

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/content/yolov5/models/yolo.py in forward(self, x, augment, profile)
    121             return self.forward_augment(x)  # augmented inference, None
    122         else:
--> 123             return self.forward_once(x, profile)  # single-scale inference, train
    124 
    125     def forward_augment(self, x):

/content/yolov5/models/yolo.py in forward_once(self, x, profile)
    152                 logger.info(f'{dt[-1]:10.2f} {o:10.2f} {m.np:10.0f}  {m.type}')
    153 
--> 154             x = m(x)  # run
    155             y.append(x if m.i in self.save else None)  # save output
    156 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/content/yolov5/models/yolo.py in forward(self, x)
     59 
     60                 y = x[i].sigmoid()
---> 61                 if self.inplace:
     62                     y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
     63                     y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    946                 return modules[name]
    947         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 948             type(self).__name__, name))
    949 
    950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'Detect' object has no attribute 'inplace'`

 How can I solve it?

**Comment by akshay-gupta123** [comment]
@emamangiapia can you share your code ?
